name: Release for windows
on:
  push:
    tags:
      - v*
  workflow_dispatch:

jobs:
  build-n-publish:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@master
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: "3.10"
    - name: Build
      run: |
        python -m pip install --upgrade pip
        pip install pyqt5
        pip install pyinstaller
        pip install -e .[win32,battery]
    - name: Bundle
      run: |
        make bundle
    - name: Archive
      run: |
        powershell Compress-Archive dist/FeelUOwn dist/FeelUOwn-win64.zip
    - name: Upload
      if: startsWith(github.ref, 'refs/tags/v')
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: dist/FeelUOwn-win64.zip
